baseURL = "https://dexter816.github.io/"
languageCode = "en-us"
theme = "hyde"
title = "Deepika Upadhyay"
[params]
disqusShortname = "dexter816"
googleAnalytics = ""
layoutReverse = false
publishDir = "docs"
theme = "hyde"
themeColor = "theme-base-09"
