baseURL = "https://dexter816.github.io/"
languageCode = "en-us"
theme = "hyde"
title = "Deepika Upadhyay"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-09"
