baseURL = "https://dexter816.github.io/hyde-hugo-starter/"
languageCode = "en-us"
theme = "hyde"
title = "Deepika Upadhyay"
[params]
disqusShortname = "dexter816"
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-09"
