baseURL = "http://dexter816.github.io"
languageCode = "en-us"
theme = "hyde"
title = "Deepika Upadhyay"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
